apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: volca-api
  name: volca-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volca-api
  template:
    metadata:
      labels:
        app: volca-api
    spec:
      containers:
      - image: registry.hub.docker.com/tuanpa1993/volca-api:$VOLCA_API_TAG
        imagePullPolicy: Always
        name: volca-api
---
apiVersion: v1
kind: Service
metadata:
  name: volca-api-service 
  namespace: default
  labels:
    app: volca-api
spec:
  type: LoadBalancer
  selector:
    app: volca-api
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80